services:
# php service
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html 
    ports:
      - 8080:80 
    depends_on:
      - mongodb
    restart: always

  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  # MongoDB Express service
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongodb:27017/
    links:
      - mongodb
    depends_on:
      - mongodb

